config/routes.rb
Rails.application.routes.draw do
  root "user#profile" 
  get 'profile', to: :show, controller: 'user'
  
  devise_for :users
  resources :user, shallow: true do
  	resources :tascs
  end

  resources :groups, shallow: true do
    post 'add_group' ,to: :add_group, controller: 'groups' 
    post 'dell_user' ,to: :dell_user, controller: 'groups' 
    post 'add_chef' ,to: :add_chef, controller: 'groups' 
    resources :tascs
  	resources :user 
  end



end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/group.rb
class Group < ApplicationRecord
	has_many 	:users
	has_many 	:tascs, dependent: :destroy
end

app/models/tasc.rb
class Tasc < ApplicationRecord
	
	belongs_to :group
	belongs_to :user

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_attached_file :user_avatar
	validates_attachment_content_type :user_avatar, content_type: /\Aimage\/.*\z/

  has_many 		:tascs, dependent: :destroy
  belongs_to	:group


  	def self.when_birthday
  		FirstJob.perform_later
  	end

  	def self.bd_user_soon
  		User.all.each do|user|
	  		unless (user.birthday_user.nil?)
				birthday = user.birthday_user.utc
				now = Time.now.utc.change(hour: 21)
				birthday_to = birthday.change(year: now.year, hour: 21 )+1.year

				birthday_soon = birthday_to.to_i - now.to_i
				birthday_soon = sec2d(birthday_soon)
				
				if birthday_soon == 365
					TaskMailer.birthday(user).deliver
					TaskMailer.birthday_soon(user, birthday_soon).deliver
				elsif birthday_soon <= 5
					TaskMailer.birthday_soon(user, birthday_soon).deliver
				end
			end
		end
	end

	def self.sec2d(seсs)
		days 	= 	seсs.round      
		days 	/= 	86400                              
		days    
	end


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	
  protect_from_forgery with: :exception
  before_action :authenticate_user!
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController

	helper_method :find_group

	
	def add_chef
		@group = Group.find(params[:group_id])
		User.where(chef: @group.id)
		User.update(chef: 0)
		@user = User.find(params[:user_id])
		@user.update(chef: @group.id)
		redirect_to group_path(@group)
	end


	def add_group
		@user = User.find(params[:user_id])
		@group = Group.find(params[:group_id])

		@user.group = @group

		@user.update(group_id: @group.id)
		redirect_to group_path(@group)
	end

	def dell_user
		@user = User.find(params[:user_id])
		@group = Group.find(params[:group_id])

		@user.update(group_id: 0 )
		redirect_to group_path(@group)
	end








	def index
		@group 	= GroupDecorator.decorate_collection(Group.all)
	end

	def new
		@group = Group.new
	end

	def create
		@group = Group.new(group_param)
		if @group.save
			redirect_to groups_path
		else
			render :new
		end
	end

	def edit
		find_group
	end

	def show
		@group 	= find_group.decorate
		@user 	= find_group.users.all
		@tasc 	= find_group.tascs.all.order("id DESC").limit(3)
		@chef	= User.where(chef: @group.id)
		@user_all = User.all

	end


	def update
		if find_group.update(group_param)
			redirect_to group_path
		else
			render :edit
		end
	end


	def destroy
		if find_group.destroy
			redirect_to groups_path
		else
			redirect_to groups_path
		end
	end

	private
		def find_group
			@group ||= Group.find(params[:id]) 
		end
		def group_param
			params[:group].permit(:group_name,:user_id)
		end

end

app/controllers/tascs_controller.rb
class TascsController < ApplicationController

	helper_method :find_tasc, :find_who

	def index

		if params[:user_id] 

			if find_user == current_user || current_user.admin == 1
				@tasc = find_user.tascs.where(params[:user_id]).order("id DESC")
			else
				redirect_to user_path(find_user)
			end

		else
			if current_user.admin == 1 || current_user.group_id == find_group.id 
				@tasc = find_group.tascs.all.order("id DESC")
			else
				redirect_to group_path(find_group)
			end
		end

	end


	def new
		@tasc = Tasc.new
	end


	def create
		if params[:user_id]	
			p find_user	
			p @tasc = find_user.tascs.create(tasc_param)	 
			if @tasc.save
				redirect_to user_path(find_user)
				TaskMailer.task_created(@tasc).deliver_later
			else
				render :new
				puts "in user"
			end

		else
			@tasc = find_group.tascs.create(tasc_param) 
			if @tasc.save
				redirect_to group_path(find_group)
				TaskMailer.task_created_group(@tasc, find_group).deliver_later
			else
				render :new
			end
		end
	end

	def edit
		find_tasc
	end

	def update
		if find_tasc.update(tasc_param)
			redirect_to user_tascs_path
		else
			render :edit
		end
	end

	def destroy
		if params[:group_id]
			@group = find_tasc.group
			if find_tasc.destroy
				redirect_to group_tascs_path(@group)
			else
				redirect_to group_tascs_path(@group)
			end
		else
			@user = find_tasc.user
			if find_tasc.destroy
				redirect_to user_tascs_path(@user)  
			else
				redirect_to user_tascs_path(@user)
			end
		end
	end

	private
		def tasc_param
			params[:tasc].permit(:task_name, :text, :group_id, :user_id)
		end

		def find_user
			@user ||= User.find(params[:user_id])
		end

		def find_group
			@group ||= Group.find(params[:group_id])
		end


		def find_tasc
			@tasc ||= Tasc.find(params[:id])
		end


		def find_who
			@tasc ||= if params[:user_id]						
				find_user 
			else
				find_group
			end
		end
end

app/controllers/user_controller.rb
class UserController < ApplicationController

	helper_method :find_user

	def profile
		@user = current_user.decorate
		@tasc = find_user.tascs.order("id DESC").limit(3)
	end
	

	def index
		@users = UserDecorator.decorate_collection(User.all)
		 
	end

	def edit
		find_user
	end

	def show
		@user = find_user.decorate
		@tasc 	= find_user.tascs.order("id DESC").limit(3)
		if current_user == find_user
			redirect_to root_path
		end
	end

	def update
		@user = find_user
		@user_all = User.all
		if @user.position_in_company != params[:user][:position_in_company] &&  find_user.update(user_param) 
			redirect_to user_path

			TaskMailer.position_in_company_changed(@user).deliver_later

		elsif find_user.update(user_param)
			redirect_to user_path
		else
			render :edit
		end

	end

	def destroy
		if find_user.destroy
			redirect_to user_index_path
		else
			redirect_to user_index_path
		end
	end



	private
		

		def find_user
			@user ||= User.find(params[:id])
		end

		def user_param
			params[:user].permit(:name_user,:position_in_company,:phone_user,:email,:birthday_user,:about_user,:user_avatar,:user_id,:group_id)
		end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/groups/_form.html.slim
= simple_form_for @group, html: { class: "simple-form" } do |f|
	=f.input :group_name
	=f.button :submit, 'ok', class: 'btn btn-success'
end

app/views/groups/edit.html.slim
h1 редактировать группу
=render partial: "groups/form"

app/views/groups/index.html.slim
.col-md-12
	h1 Отделы компании
	table class="table"
		tr
			th Название отдела
			th Глава отдела
			th 
			th
		-@group.each do |g|
			tr
				td =g.group_name
				td =g.group_chef(g)			
				td =g.more_btn
				td =g.add_group_btn(current_user)

	-if current_user.admin == 1
		=link_to "Создать новый отдел", new_group_path, class: "btn btn-success"

app/views/groups/new.html.slim
h1 Новая группа
=render partial: "groups/form"

app/views/groups/show.html.slim
.col-md-12
	h1 В вашей группе #{@group.group_name}

	div class="panel panel-info"
		div class="panel-heading"
			h2 class="panel-title" style="color: #337ab7;" Задачи отдела #{@group.group_name}
		div class="panel-body"	
			-@tasc.each do |t|
				div class="panel panel-primary"
					div class="panel-heading"
						h3 class="panel-title" =t.task_name
					div class="panel-body"
						p =t.text
						p =@group.group_tasc_del(current_user,t)

			=link_to "Все задачи", group_tascs_path(@group), class: "btn btn-success"
			-if current_user.chef == @group.id || current_user.admin == 1
				td =link_to "Добавить задачу", new_group_tasc_path(@group), class: "btn btn-warning"

				
	div class="panel panel-info"
		div class="panel-heading"
			h2 class="panel-title" style="color: #337ab7;" Команда отдела #{@group.group_name}
			
			-@chef.each do |c|
				p  Глава отдела #{c.name_user}

		div class="panel-body"	
					
				table class="table"
					tr
						th Имя 
						th Должность
						th Телефон
						th Почта
						th
						th 
					
					-@user.each do |u|
						tr
							td =u.name_user
							td =u.position_in_company
							td =u.phone_user
							td =u.email
							td =link_to "Профиль", user_path(u), class: "btn btn-success"
							td =@group.add_chef_btn(current_user,u)
							td =@group.del_btn_group(current_user,u)


				-if current_user.chef == @group.id || current_user.admin == 1
					h4 Все пользователи
					table class="table"
						tr
							th Имя 
							th Должность
							th Телефон
							th Почта
							th
							th
						
						-@user_all.each do |u|
							tr
								td =u.name_user
								td =u.position_in_company
								td =u.phone_user
								td =u.email
								td =@group.more_info_btn(u)
								td =@group.add_to_group_btn(u)

app/views/layouts/_nav.html.slim
div class="navbar navbar-default navbar-fixed-top"
  div class="container"
    div class="navbar-header"
      =link_to 'My Crm', root_path, class: 'navbar-brand'
      button class="navbar-toggle" type="button" data-toggle="collapse" data-target="#navbar-main"
        span class="icon-bar"
        span class="icon-bar"
        span class="icon-bar"
      
    div class="navbar-collapse collapse" id="navbar-main"
      ul class="nav navbar-nav"
        li class="dropdown"
          a class="dropdown-toggle" data-toggle="dropdown" href="#" id="themes" Компания <span class="caret"> </span>
          ul class="dropdown-menu" aria-labelledby="themes"
            li =link_to 'Пользователи',user_index_path
            li class="divider"
            li =link_to 'Отделы' ,groups_path

        -unless current_user.group.blank?
          li  =link_to 'Отдел', group_path(current_user.group)
        -unless current_user.tascs.blank?
          li  =link_to 'Задачи', user_tascs_path(current_user)      
    
      ul class="nav navbar-nav navbar-right"
        -if current_user
          li  = link_to 'Выход', destroy_user_session_path, method: :delete 
        -else
          li = link_to 'Регистрация', new_user_registration_path 
          li = link_to 'Вход', new_user_session_path 
        

app/views/layouts/application.html.slim
doctype html
html
  head
    title Crm
    = csrf_meta_tags 
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' 
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload' 
    

  body
    -if current_user
      = render partial: "layouts/nav"
    p.notice = notice
    p.alert = alert 
    .container
      .row
        == yield

    
  

app/views/tascs/_form.html.slim
-if params[:user_id]
	= simple_form_for @tasc, url: user_tascs_path, html: {class: "simple-form"} do |f|
		=f.input :task_name, 	label: 'Task'
		=f.input :text,			label: 'Task text'
		=f.button :submit, 'ok'
-else
	= simple_form_for @tasc, url: group_tascs_path, html: {class: "simple-form"} do |f|
		=f.input :task_name, 	label: 'Task'
		=f.input :text,			label: 'Task text'
		=f.button :submit, 'ok'

app/views/tascs/edit.html.slim
h1 tasc
= render partial: "tascs/form"

app/views/tascs/index.html.slim
.col-md-12
	-if params[:user_id]
		h1 Ваши задачи #{ @user.name_user }
	-else
		h1 Все задачи #{ @group.group_name }
	
	- @tasc.each do |t|
		div class="panel panel-primary"
		 	div class="panel-heading"
				h3 class="panel-title" =t.task_name
			div class="panel-body"
				p =t.text



			-if params[:user_id]
				-if current_user.admin == 1 || current_user.chef == @user.group_id && current_user.chef != 0					
					= link_to 'Удалить задание', tasc_path(t), method: :delete ,class: "btn btn-danger"
			-else
				-if current_user.admin == 1 || current_user.chef == @group.id && current_user.chef != 0	
					= link_to 'Удалить задание', tasc_path(t, group_id: @group), method: :delete ,class: "btn btn-danger"
			


	-if params[:user_id]
		-if current_user.admin == 1 || (current_user.chef == @user.group_id && current_user.chef != 0)	
			= link_to "Добавить Задание", new_user_tasc_path(@user) ,class: "btn btn-success"
	-else
		-if current_user.admin == 1 || current_user.chef == @group.id && current_user.chef != 0	
			= link_to "Добавить Задание", new_group_tasc_path(@group) ,class: "btn btn-success"
			
	end

app/views/tascs/new.html.slim
h1 new
= render partial: "tascs/form"

app/views/user/_info_user.html.slim
.col-md-4
	=@user.user_avatar
	h1 = @user.user_title
.col-md-8
	

	div class="panel panel-primary"
	 	div class="panel-heading"
			h3 class="panel-title" Должность в компании
		div class="panel-body"
			p Должность #{@user.user_position}
			h5 отдел #{@user.user_group}
			 

	div class="panel panel-primary"
		 	div class="panel-heading"
				h3 class="panel-title" Контактная информация
			div class="panel-body"
				p тел: #{ @user.user_phone}
				p почта: #{ @user.email} 

	div class="panel panel-primary"
		 	div class="panel-heading"
				h3 class="panel-title" Личные данные
			div class="panel-body"
				p день рождения #{@user.user_birthday}
				h4 Немного о себе
				p = @user.user_about

	=@user.edit_button(current_user)
	
-if @tasc.present? || current_user.admin == 1 || current_user.chef == @user.group_id && current_user.chef != 0
	.col-md-12
		h2 Последние задания
		-@tasc.each do |t|
			div class="panel panel-primary"
				div class="panel-heading"
					h3 class="panel-title" = t.task_name
				div class="panel-body"
					p =  t.text

		
		=@user.all_tasc_btn(current_user)
		=@user.add_task_btn(current_user)

app/views/user/edit.html.slim
h1 Edit
= simple_form_for @user, html: { class: "simple-form" } do |f|
	=f.input :user_avatar, as: :file, 	label: 'avatar'
	=f.input :name_user, 				label: 'you name'
	-if current_user.admin == 1
		=f.input :position_in_company, 		label: 'position'
	-else
		=@user.position_in_company if @user.position_in_company.present?
	 
	=f.input :phone_user, 				label: 'you phone'
	=f.input :email,					label: 'email'
	=f.input :birthday_user, 			label: 'birthday', as: :date, start_year: Date.today.year - 90,end_year: Date.today.year - 12, discard_day: false,order: [:month, :year, :day] 
	=f.input :about_user, 				label: 'about you'
	=f.button :submit, 'ok', class: 'btn btn-success'
end

app/views/user/index.html.slim
.col-md-12
	h1 Все пользователи компании
	table class="table"
		tr
			th Имя
			th Должность
			th Отдел
			th Телефон
			th 
			th
		-@users.each do |user|
			tr
				td =user.user_title
				td =user.user_position

				td =user.user_group

				td =user.user_phone
				td =user.profel_btn
				td =user.del_user_btn(current_user)
		end

app/views/user/profile.html.slim
=render partial: "user/info_user"

app/views/user/show.html.slim
=render partial: "user/info_user"